name: grzegorz
channels:
    - conda-forge
dependencies:
  - numpy
  - pandas
  - jupyter
  - numpy-financial
  - Django
  - backports.zoneinfo
  - openpyxl
  - seaborn
  - pip
  - pip:
    - dataframe-image
    - python-slugify
    - dict_hash[all] 
