name: car-compare 
channels:
    - conda-forge
dependencies:
  - numpy
  - pandas
  - jupyter
  - numpy-financial
  - Django
  - backports.zoneinfo
  - openpyxl
  - seaborn
  - black
  - flake8
  - mypy
  - pre-commit
  - pip
  - pip:
    - dataframe-image
    - python-slugify
    - google-api-python-client
    - google-auth-httplib2 
    - google-auth-oauthlib
